###################################################### 
# Options to build using
# Standard C++ Library (e.g. RedHat Linux 8.0 and later)
######################################################

### Commands
SHELL = /bin/sh
CP = cp
RM = rm -f

### Test Name
TEST_NAME = TestGetters

### Directories for the test
ROOTDIR = $(PWD)
DATADIR = $(ROOTDIR)/../data
TEST_LOG = $(ROOTDIR)/$(TEST_NAME).OUT

### Location of Stochsim includes, library and executable
LIBDIR = $(ROOTDIR)/../../../lib/
SRCDIR = $(ROOTDIR)/../../../src/
BINDIR = $(ROOTDIR)/../../../bin/
STOCHSIM_LIB = stochsim

### Compiler
CXX = g++
OPTS = -D_STD_CPP -D_UNIX -D_AVERAGING
CXXFLAGS = -O3 -Wno-deprecated -Wall -fPIC 
#CXXFLAGS = -g -Wno-deprecated -Wall -fPIC 


### Running the Test
all: $(TEST_NAME)
	-mkdir $(DATADIR)/cell1/Output
	export LD_LIBRARY_PATH=$(LIBDIR); \
	echo " " > $(TEST_LOG); \
	echo "TEST RESULTS" >> $(TEST_LOG); \
	echo " " >> $(TEST_LOG); \
	echo "We are testing the getters."  >> $(TEST_LOG); \
	echo " " >> $(TEST_LOG); \
	echo "************************************************" >> $(TEST_LOG); \
	cd $(DATADIR)/cell1/Input; $(ROOTDIR)/$(TEST_NAME) >> $(TEST_LOG); \
	echo " " >> $(TEST_LOG); \
	echo "************************************************" >> $(TEST_LOG); \
	cat $(TEST_LOG)


### Compiling the test
$(TEST_NAME):  
	$(CXX) $(CXXFLAGS) $(OPTS) -I$(SRCDIR) -o $(TEST_NAME) $(TEST_NAME).cpp -L$(LIBDIR) -l$(STOCHSIM_LIB)


### Cleaning 
.PHONY: clean
clean:
	rm -f $(DATADIR)/cell?/Output/*.OUT *.o $(TEST_NAME) $(TEST_LOG)